'use strict';

/*
 * Generates the daily chess puzzles: plays bot-vs-bot games and keeps positions
 * where the side to move has exactly one move that forces mate in 2 (and no mate in 1).
 * Every puzzle is therefore correct by construction. To keep them interesting, the
 * board must still be busy and the attacker can't simply be miles ahead on material.
 *
 *   node tools/gen-puzzles.js [count=120] [threads=CPU count]  -> writes js/games/chess-puzzles.js
 *
 * The file is rewritten after every new puzzle, so a long run can be stopped at any point.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const { Worker, isMainThread, parentPort } = require('worker_threads');
const E = require('../js/games/chess-engine.js');

const VALUE = { P: 1, N: 3, B: 3, R: 5, Q: 9, K: 0 };

function interesting(s) {
  let pieces = 0;
  let balance = 0; // from the side to move's point of view
  for (const p of s.board) {
    if (!p) continue;
    pieces++;
    const mine = (p === p.toUpperCase()) === (s.turn === 'w');
    balance += (mine ? 1 : -1) * VALUE[p.toUpperCase()];
  }
  return pieces >= 12 && balance <= 4;
}

// Plays one bot-vs-bot game and returns the first puzzle position found, or null.
function puzzleFromOneGame() {
  let s = E.initial();
  for (let ply = 0; ply < 160; ply++) {
    if (!E.legalMoves(s).length) return null;
    if (ply >= 16 && interesting(s) && !E.canMate(s, 1) && E.matingMoves(s, 2).length === 1) {
      return E.toFEN({ ...s, half: 0, full: 1 }); // reset counters so the puzzle reads cleanly
    }
    const m = E.bestMove(s, { depth: 2, timeMs: 300, randomness: 0.08 });
    s = E.legalMoves(s).find((x) => x.from === m.from && x.to === m.to && x.promo === m.promo).next;
  }
  return null;
}

if (!isMainThread) {
  for (;;) {
    const fen = puzzleFromOneGame();
    parentPort.postMessage(fen);
  }
}

const target = +process.argv[2] || 120;
const threads = +process.argv[3] || os.cpus().length;
const found = new Map(); // position (FEN without counters) -> FEN
const started = Date.now();
let games = 0;

function write() {
  const out = `'use strict';

// Mate-in-2 puzzles, one per day. Generated by tools/gen-puzzles.js — every
// position has exactly one first move that forces mate in 2.
const CHESS_PUZZLES = ${JSON.stringify([...found.values()], null, 2)};

if (typeof module !== 'undefined') module.exports = CHESS_PUZZLES;
`;
  fs.writeFileSync(path.join(__dirname, '../js/games/chess-puzzles.js'), out);
}

const workers = Array.from({ length: threads }, () => new Worker(__filename));
for (const w of workers) {
  w.on('message', (fen) => {
    games++;
    if (!fen || found.size >= target) return;
    const key = fen.split(' ').slice(0, 4).join(' ');
    if (found.has(key)) return;
    found.set(key, fen);
    write();
    process.stdout.write(`\r${found.size}/${target} puzzles from ${games} games (${Math.round((Date.now() - started) / 1000)}s)`);
    if (found.size >= target) {
      console.log(`\nWrote ${found.size} puzzles to js/games/chess-puzzles.js`);
      for (const x of workers) x.terminate();
    }
  });
}
